### ISSUE TITLE
Add contributors in Readme File

### ISSUE THREAD

**Issue by PranavMasekar** [nsccpccoe/nscc-backend#16]

**Comment by the-amazing-atharva** [comment]
I would like to add contributors to the README.md file

I am a beginner here and would like to help with the documentation

**Comment by PranavMasekar** [comment]
Sure go ahead and assign this issue to yourself by typing "/ assign" without space ... You can take reference from NSCC app repository

**Comment by the-amazing-atharva** [comment]
/ assign

**Comment by the-amazing-atharva** [comment]
Hey thanks for the reply

I have linked a PR
